### ISSUE TITLE
Warnings and README improvements

### ISSUE THREAD

**Issue by gabrielgg** [rinigus/pkg-mapnik#4]
I found some potential improvements that can be done, albeit nothing is actually broken:
- There are 2 %files macros (rpm/mapnik.spec:80) generating a warning - one can be safely deleted in my tests.
- There is a macro in a comment (rpm/mapnik.spec:94) generating a warning - this can be deleted (I don't know why rpmbuild doesn't simply treat the comment as a comment)
- In README.md, I understand "source directory" as mapnik/ - something fails if you start the build from there, so I started from the root of the project and removed "../" from the subsequent instruction; also, the target doesn't match modern ones, so I would just instruct the user here to select a valid target.  I do understand that this hasn't been updated for a year or two though :)

**Comment by rinigus** [comment]
Feel free to submit the changes as PR, please.

**Comment by gabrielgg** [comment]
One more thing... I'm not sure whether the comments about the but in the i486 target are still relevant; at least I didn't have to do anything in 3.4.  Happy to take those out if you think they are no longer relevant.

**Comment by rinigus** [comment]
Fixed in #5

**Comment by Thaodan** [comment]
> * There is a macro in a comment (rpm/mapnik.spec:94) generating a warning - this can be deleted (I don't know why rpmbuild doesn't simply treat the comment as a comment)

The macro still gets expanded. You should escape `%` in RPM specfiles as `%%`.
